# Generated by Django 4.1 on 2023-05-17 22:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='contributions',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
